[project]
name = "my-first-django-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django-cors-headers>=4.6.0",
    "django>=5.1.3",
    "psycopg2-binary>=2.9.10",
    "djangorestframework>=3.15.2",
]
